# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  # Definir a escolha da Box
  config.vm.box = "ubuntu/jammy64"
  # (Opcional) Definir a versão da Box
  config.vm.box_version = "20221014.0.0"
  # Hostname da VM
  config.vm.hostname = "ubuntu2204"


  config.vm.provider "virtualbox" do |vb|
    # Nome de identificação da VM no VirtualBox
    vb.name = "ubuntu-jammy"
    # Quantidade de CPUs
    vb.cpus = "2"
    # Quantidade de memória RAM:
    vb.memory = "4096"
    # Ajustes de vídeo
    vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
    vb.customize ['modifyvm', :id, '--vram', '64']
    # Exibir GUI quando inicializar a VM
    vb.gui = true
  end
  
  # Adicionar o usuário `vagrant` ao grupo `sudo`
  config.vm.provision :shell, inline: "sudo usermod -a -G sudo vagrant"

  # Arquivo com o script de instalação
  config.vm.provision "ubuntu shell script", type: "shell", path: "scripts/config.sh", privileged: false
end
